services:
  - type: web
    name: mew-mew-pos
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install && pnpm run build:all
    startCommand: pnpm start
    healthCheckPath: /api/auth/me
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_PATH
        value: /
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
