import { Router, type IRouter } from "express";
import healthRouter from "./routes/health";
import authRouter from "./routes/auth";
import productsRouter from "./routes/products";
import customersRouter from "./routes/customers";
import transactionsRouter from "./routes/transactions";
import dashboardRouter from "./routes/dashboard";
import suppliersRouter from "./routes/suppliers";
import purchasesRouter from "./routes/purchases";
import categoriesRouter from "./routes/categories";
import employeesRouter from "./routes/employees";
import expensesRouter from "./routes/expenses";
import assetsRouter from "./routes/assets";
import quotationsRouter from "./routes/quotations";
import inventoryRouter from "./routes/inventory";
import reportsRouter from "./routes/reports";
import usersRouter from "./routes/users";
import settingsRouter from "./routes/settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(transactionsRouter);
router.use(dashboardRouter);
router.use(suppliersRouter);
router.use(purchasesRouter);
router.use(categoriesRouter);
router.use(employeesRouter);
router.use(expensesRouter);
router.use(assetsRouter);
router.use(quotationsRouter);
router.use(inventoryRouter);
router.use(reportsRouter);
router.use(usersRouter);
router.use(settingsRouter);

export default router;
